### ISSUE TITLE
[BUG] The optional field in the help slash command is useless

### ISSUE THREAD

**Issue by GoudronViande24** [NamVr/DiscordBot-Template#11]
**Describe the bug**
When you use the help slash command with the "command" option, it changes nothing and still responds only the "general help".

**To reproduce**
- Start the bot
- Execute `/help [anything]`
- Whatever you write, it's still going to answer the same as if you put nothing

**Expected behaviour**
It should do like the traditional `!help` command, general help when no options, and help about a specific command when given.

**Comment by NamVr** [comment]
Oh, I can reproduce that clearly. Thank you for the report. I'll make this change ASAP.

**Comment by GoudronViande24** [comment]
Thank you! I'll probably add this to my bot when it's done.

**Comment by NamVr** [comment]
Just to let you know, I have trouble with my pc so yea might take some time

**Comment by GoudronViande24** [comment]
No problem 👍

**Comment by NamVr** [comment]
I will need someone to contribute :pray:

**Comment by GoudronViande24** [comment]
I will soon! 👍

**Comment by GoudronViande24** [comment]
There you go: #13

**Comment by NamVr** [comment]
Fixed in #13
