### ISSUE TITLE
[BUG] guildMemberUpdate not emitting

### ISSUE THREAD

**Issue by kingpin24** [NamVr/DiscordBot-Template#15]
Hi,

I've placed a guildMemberUpdate.js file under events, with this being the basic code in it:

```const { db } = require("./../bot");
const { MessageEmbed } = require("discord.js");

module.exports = {
    name: "guildMemberUpdate",

    execute: async (oldMember, newMember) => {
        console.log("test");
    },
};
```

for some reason, "test" is not being printed in the console whenever i remove or add a role to a member

**Comment by NamVr** [comment]
Double check the code structure. It is wrong.

**Comment by NamVr** [comment]
js```
module.exports = {
    name: "guildMemberUpdate",

    async exexute(oldMember, newMember) => {
        console.log("test");
    },
};
```
