### ISSUE TITLE
[BUG] guildMemberAdd not emitting

### ISSUE THREAD

**Issue by JnnDougg** [NamVr/DiscordBot-Template#19]
I tried to use the event but the print 'test' did not appear

```
/**
 * @file Context Interaction Handler
 * @author Krish Garg & Naman Vrati
 * @since 3.0.0
 * @version 3.3.0
 */

module.exports = {
	name: "guildMemberAdd",

	/**
	 * @description Executes when client is ready (bot initialization).
	 * @param {import('../typings').Client} client Main Application Client.
	 */
	execute(client, guild, member) {
        console.log('test')
	},
};
```

**Comment by NamVr** [comment]
Hi @JnnDougg,

I'm pretty sure we have zero bugs in our template handler. Here is what I would suggest:
- Your code seems to be copied from context menu handler file, please note the parameters are different for each event. Check the documentation of [`guildMemberAdd`](https://discord.js.org/#/docs/discord.js/main/class/Client?scrollTo=e-guildMemberAdd) event, and you can see only `member` parameter is present.

- The "test" should be printed whenever a new guild member has been added/joined your guild. In your case, I feel this event is not even triggering, there can be several problems related to it, like your bot not having appropriate permissions in your guild, your bot doesn't have the `GuildMembers` intent enabled in [Discord Developers Dashboard](discord.com/developers/applications/) & most common fix is that you have forgot to add/enable the `GuildMembers` intent in your `bot.js` file.

Let me know if that helps!
