### ISSUE TITLE
Slash Commands Permissions 

### ISSUE THREAD

**Issue by pronthox** [NamVr/DiscordBot-Template#21]
Hi,
Now that we have .`setDefaultMemberPermissions` to set permissions for commands in `SlashCommandBuilder` for slash commands. How can I check if check if the user typing the command has the command? I was thinking about the help command to list all commands so I can only display available commands for the user typing the command. 

Example if one command has `.setDefaultMemberPermissions(PermissionFlagsBits.BanMembers)`, and a user without that permission types the help command in slash to list all available commands. How can we hide that command from being displayed as the user doesnt have access?

**Comment by NamVr** [comment]
Hi @pronthox, can I get documentation references to each :)

**Comment by NamVr** [comment]
Nevermind that, I think you are asking for discord.js support instead. So basically when you use `setDefaultMemberPermissions`, the command gets grayed out for those who can't use it. AFAIK, discord doesn't provide a way to "hide" such commands.
And, about the help command, it is going to be a little complex for it, but I'm sure you can just introduce a new permissions property in slash commands to make it work out, OR check [permissions](https://discord.js.org/#/docs/discord.js/main/class/ApplicationCommand?scrollTo=permissions) of that slash command. In our case, we will "filter" all `slashCommands` in the help command with property permissions with current author permissions to get a new array of commands.

I hope that helps!
