### ISSUE TITLE
Suggestion: Add sharding

### ISSUE THREAD

**Issue by LightningBolt62** [NamVr/DiscordBot-Template#6]
It'd be great if you could add sharding to this! Either auto or manual(like an option for us in [`config.json`](https://github.com/NamVr/DiscordBot-Template/blob/master/config.json) to enable/disable sharding). 

There is a package I know of, [Discord-Hybrid-Sharding](https://www.npmjs.com/package/discord-hybrid-sharding), that allows you to save a lot of resources while sharding(up to 60% resources 
can be saved!). Maybe it could be used?

**Comment by NamVr** [comment]
Hi, thanks for your suggestion.

> There is a package I know of, Discord-Hybrid-Sharding, that allows you to save a lot of resources while sharding(up to 60% resources
can be saved!). Maybe it could be used?

Well, I'd say _no_ because my target of this project was "zero-external-dependencies", and I am maintaining that! So, uh - I'll most likely follow discord.js itself _(while no one stops you on your project to use any kind of module)_

And yes, your suggestion is a worth to be added in the template. Would you possibly like to contribute? Please let me know + Feel free to open PR as well!

Otherwise, I'll look into it :)

**Comment by LightningBolt62** [comment]
> Well, I'd say _no_ because my target of this project was "zero-external-dependencies", and I am maintaining that! So, uh - I'll most likely follow discord.js itself _(while no one stops you on your project to use any kind of module)_

Okie then! That makes sense.

> And yes, your suggestion is a worth to be added in the template. Would you possibly like to contribute? Please let me know + Feel free to open PR as well!

I'd love to contribute! But I don't have any experience in sharding yet, as my bot dosen't require it. I'm still learning.
However, If there's anything that I feel like I can do, I would, of course, contribute. 
> Otherwise, I'll look into it :)

That'd be awesome! Thanks a lot :D

**Comment by NamVr** [comment]
> > Well, I'd say _no_ because my target of this project was "zero-external-dependencies", and I am maintaining that! So, uh - I'll most likely follow discord.js itself _(while no one stops you on your project to use any kind of module)_
> 
> Okie then! That makes sense.
> 
> > And yes, your suggestion is a worth to be added in the template. Would you possibly like to contribute? Please let me know + Feel free to open PR as well!
> 
> I'd love to contribute! But I don't have any experience in sharding yet, as my bot dosen't require it. I'm still learning.
> However, If there's anything that I feel like I can do, I would, of course, contribute.
> 
> > Otherwise, I'll look into it :)
> 
> That'd be awesome! Thanks a lot :D

Alright yeah, I'll make something out of it, s00n™

**Comment by NamVr** [comment]
> References: 
> https://discordjs.guide/sharding/#how-does-sharding-work
> https://discord.js.org/#/docs/main/stable/typedef/ClientOptions

As I look in shards, it is pretty easy to internal shard your bot automatically. 

As part of discordjs.guide:
> Apart from ShardingManager, discord.js also supports a sharding mode known as Internal sharding. Internal sharding creates multiple websocket connections from the same process, and does not require major code changes. To enable it, simply pass `shards: 'auto'` as ClientOptions to the Client constructor. However, internal sharding is not ideal for bigger bots due to high memory usage of the single main process and will not be further discussed in this guide.

Simply add the property in [`bot.js`](https://github.com/NamVr/DiscordBot-Template/blob/master/bot.js#L22 "Define Client in main bot file")

```diff
const client = new Client({
	intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES],
+	shards: 'auto', 
});
```

And, hope that works! And as part of adding in project, I say I would not like to add it but simply add it in the documentation I'm working on, https://djs-template.docs.namanvrati.cf/
Let me know any more questions.

Cheers!
