### ISSUE TITLE
[HELP] Unwanted Slash Interactions Visible

### ISSUE THREAD

**Issue by FallOsprey** [NamVr/DiscordBot-Template#7]
When I run the bot and look at the slash commands through Discord, I see is has commands like **/admin embed**, **/admin say**, **/info ping**, and **/info userinfo**. I want to get rid of these but I can't find them anywhere in the bots files. 
![2021-10-17 (2)](https://user-images.githubusercontent.com/68159855/137638517-78a82380-c0c3-4386-84ad-11898f6392a8.png)

**Comment by FallOsprey** [comment]
Yes

**Comment by FallOsprey** [comment]
![2021-10-17 (4)](https://user-images.githubusercontent.com/68159855/137638680-e139aea8-a272-44cd-8876-851f97fbe432.png)
Just that

**Comment by NamVr** [comment]
> ![2021-10-17 (7)](https://user-images.githubusercontent.com/68159855/137638767-20f1889b-d6eb-486f-ae76-4370ace390b8.png) All command interactions fail (except help). I have restarted the bot multiple times. I don't understand number 3

This indeed means that the commands are actually not available. You should try restarting your discord client (discord app), do <kbd>Ctrl</kbd> + <kbd>R</kbd> also try restarting your network connection. I don't see this issue from the coding side.

**Comment by NamVr** [comment]
Please explain in brief.

**Comment by NamVr** [comment]
I believe this is caching then, did you made the commands global? or it is guild based?

**Comment by FallOsprey** [comment]
Routes.applicationGuildCommands(client_id, test_guild_id),

**Comment by NamVr** [comment]
Yeah, looks cool for guild. I will assume you have done your config file properly.
So yeah, you can use the [`ApplicationCommand`](https://discord.js.org/#/docs/main/stable/class/ApplicationCommand?scrollTo=delete 'Read the docs :p') methods as mentioned in docs, to forcefully delete it.

**Comment by FallOsprey** [comment]
How would I do that tho

**Comment by NamVr** [comment]
Make a slash command manager? Or just raw scripts using a eval command? Anything that hits up your head will make it possible.

**Comment by NamVr** [comment]
Hit me up on discord rn `allroundernaman#3915` and I'll test it in your server. (The last thing I can offer)

**Comment by FallOsprey** [comment]
Your F requests are off, https://discord.gg/Q5KWdwNm.
